import { siteConfig } from "@/lib/config";
import type { ContentSection, DashboardSnapshot, FailureEvent, MissionSettings, Post, Profile } from "@/lib/types";

export const adminProfile: Profile = {
  id: "admin-demo-micheal",
  username: siteConfig.adminUsername,
  displayName: "Micheal",
  role: "admin",
  avatarUrl: null,
  bannerUrl: null,
  bio: "10th grade operator. Building the MIT arc one logged day at a time.",
  joinDate: "2026-05-26T00:00:00.000Z",
  socialLinks: [
    { label: "GitHub", url: siteConfig.repositoryUrl },
    { label: "Mission Log", url: "/timeline" },
  ],
  commentCount: 0,
  activityScore: 1004,
  streak: 0,
  badges: ["operator", "founder"],
  status: "online",
};

const demoUser: Profile = {
  id: "observer-demo-user",
  username: "observer_17",
  displayName: "Observer 17",
  role: "user",
  avatarUrl: null,
  bannerUrl: null,
  bio: "Tracking the climb from the ground station.",
  joinDate: "2026-05-28T11:40:00.000Z",
  socialLinks: [],
  commentCount: 0,
  activityScore: 0,
  streak: 0,
  badges: ["observer"],
  status: "offline",
};

export const defaultSections: ContentSection[] = [
  {
    id: "mission-log",
    name: "ASCENT Mission Log",
    slug: "mission-log",
    description: "The central daily transformation archive: MIT, physics, fitness, study, failures, and discipline.",
    icon: "A",
    accentColor: "#ff3b30",
    theme: "terminal",
    bannerUrl: null,
    layout: "timeline",
    visibility: "public",
    commentsEnabled: true,
    featured: true,
    archived: false,
    sortOrder: 0,
    parentId: null,
    moderatorIds: [],
    createdAt: "2026-05-26T00:00:00.000Z",
  },
  {
    id: "physics-research",
    name: "Physics Research",
    slug: "physics-research",
    description: "Research notes, derivations, problem sets, experiments, and conceptual breakthroughs.",
    icon: "P",
    accentColor: "#5aa7ff",
    theme: "physics",
    bannerUrl: null,
    layout: "research",
    visibility: "public",
    commentsEnabled: true,
    featured: true,
    archived: false,
    sortOrder: 1,
    parentId: null,
    moderatorIds: [],
    createdAt: "2026-05-26T00:00:00.000Z",
  },
  {
    id: "devlog",
    name: "Devlog",
    slug: "devlog",
    description: "Code experiments, product decisions, debugging notes, and shipped systems.",
    icon: "D",
    accentColor: "#80d68f",
    theme: "terminal",
    bannerUrl: null,
    layout: "timeline",
    visibility: "public",
    commentsEnabled: true,
    featured: true,
    archived: false,
    sortOrder: 2,
    parentId: null,
    moderatorIds: [],
    createdAt: "2026-05-26T00:00:00.000Z",
  },
  {
    id: "gym-journal",
    name: "Gym Journal",
    slug: "gym-journal",
    description: "Training logs, body metrics, consistency streaks, and physical discipline receipts.",
    icon: "G",
    accentColor: "#f97316",
    theme: "gym",
    bannerUrl: null,
    layout: "magazine",
    visibility: "public",
    commentsEnabled: true,
    featured: true,
    archived: false,
    sortOrder: 3,
    parentId: null,
    moderatorIds: [],
    createdAt: "2026-05-26T00:00:00.000Z",
  },
  {
    id: "philosophical-notes",
    name: "Philosophical Notes",
    slug: "philosophical-notes",
    description: "Quiet reflections on identity, obsession, ambition, fear, and becoming difficult to stop.",
    icon: "N",
    accentColor: "#c9b8ff",
    theme: "philosophy",
    bannerUrl: null,
    layout: "magazine",
    visibility: "public",
    commentsEnabled: true,
    featured: false,
    archived: false,
    sortOrder: 4,
    parentId: null,
    moderatorIds: [],
    createdAt: "2026-05-26T00:00:00.000Z",
  },
];

export const defaultMissionSettings: MissionSettings = {
  applicationDeadline: siteConfig.applicationDeadline,
  decisionHorizon: siteConfig.decisionHorizon,
  missionTimeZone: siteConfig.missionTimeZone,
  missedDayCutoffHour: siteConfig.missedDayCutoffHour,
  countdownLabel: "primary countdown / MIT application horizon",
  countdownDescription:
    "10th grade long-range mission. Edit this timer and mission copy from the admin console whenever the target changes.",
  operatorName: siteConfig.adminUsername,
  operatorTitle: "admin / publish authority",
  operatorBio: "Only the admin account can publish logs, moderate comments, view analytics, and upload official mission media.",
  nextActionCopy: "Publish {day} before cutoff, log study hours, attach evidence, keep the system honest.",
  failureMessageTemplate: "ASCENT-1004 FAILURE ARCHIVE: {date}. Daily public log missed before cutoff. {day} remains unpaid.",
  automationEnabled: true,
};

export const posts: Post[] = [];

export const failures: FailureEvent[] = [];

export const dashboardSnapshot: DashboardSnapshot = {
  profile: adminProfile,
  settings: defaultMissionSettings,
  sections: defaultSections,
  metrics: [
    { label: "Current streak", value: "000 days", delta: "+1 if posted before cutoff", status: "warning" },
    { label: "Today study", value: "0.0 h", delta: "target 5.0 h", status: "warning" },
    { label: "Gym consistency", value: "0%", delta: "14 day window", status: "warning" },
    { label: "Physics progress", value: "0%", delta: "mechanics unit", status: "warning" },
    { label: "Weight progress", value: "0.0 kg", delta: "awaiting baseline", status: "warning" },
    { label: "Coding progress", value: "0%", delta: "awaiting projects", status: "warning" },
  ],
  dailyMetrics: [
    { date: "May 23", studyHours: 0, gymComplete: false, physicsPercent: 0, streak: 0 },
    { date: "May 24", studyHours: 0, gymComplete: false, physicsPercent: 0, streak: 0 },
    { date: "May 25", studyHours: 0, gymComplete: false, physicsPercent: 0, streak: 0 },
    { date: "May 26", studyHours: 0, gymComplete: false, physicsPercent: 0, streak: 0 },
    { date: "May 27", studyHours: 0, gymComplete: false, physicsPercent: 0, streak: 0 },
    { date: "May 28", studyHours: 0, gymComplete: false, physicsPercent: 0, streak: 0 },
  ],
  latestPost: null,
  posts: [],
  failures: [],
  analytics: [
    { label: "Mon", visitors: 0, comments: 0, studyHours: 0, consistency: 0 },
    { label: "Tue", visitors: 0, comments: 0, studyHours: 0, consistency: 0 },
    { label: "Wed", visitors: 0, comments: 0, studyHours: 0, consistency: 0 },
    { label: "Thu", visitors: 0, comments: 0, studyHours: 0, consistency: 0 },
    { label: "Fri", visitors: 0, comments: 0, studyHours: 0, consistency: 0 },
  ],
  visitorCount: 0,
  engagementRate: 0,
};

export function findDemoProfile(username: string) {
  const normalized = username.toLowerCase();
  return [adminProfile, demoUser].find((profile) => profile.username.toLowerCase() === normalized) ?? null;
}
